[package]
name = "kairamah/registry"
description = "Simple registry system with path-based indexing."
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["test", "test.project.json", "docs", "DevPackages", "build"]

[dev-dependencies]
testez = "roblox/testez@0.4.1"