[package]
name = "kyrethia/registry"
description = "Simple registry system with path-based indexing."
version = "1.4.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["test", "test.project.json", "docs", "DevPackages", "build"]